//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOSAnalyzer {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EOSAnalyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 尝试进行广播的事件码类型未标记为事件码，类型的特性中不包含EventCodeAttribute特性。 的本地化字符串。
        /// </summary>
        internal static string EOS001AOR_Description {
            get {
                return ResourceManager.GetString("EOS001AOR_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试添加或移除事件接收者的事件码 {0} 未定义 的本地化字符串。
        /// </summary>
        internal static string EOS001AOR_MessageFormat {
            get {
                return ResourceManager.GetString("EOS001AOR_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试添加或移除事件接收者的事件码未定义 的本地化字符串。
        /// </summary>
        internal static string EOS001AOR_Title {
            get {
                return ResourceManager.GetString("EOS001AOR_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试进行广播的事件码类型未标记为事件码，类型的特性中不包含EventCodeAttribute特性。 的本地化字符串。
        /// </summary>
        internal static string EOS001B_Description {
            get {
                return ResourceManager.GetString("EOS001B_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试广播的事件码 {0} 未定义 的本地化字符串。
        /// </summary>
        internal static string EOS001B_MessageFormat {
            get {
                return ResourceManager.GetString("EOS001B_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试广播的事件码未定义 的本地化字符串。
        /// </summary>
        internal static string EOS001B_Title {
            get {
                return ResourceManager.GetString("EOS001B_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 声明的事件码类型中，至少需要有一个声明了EventCodeMethod特性的事件方法的定义声明，才能合法使用该事件码。请考虑对需要的方法添加EventCodeMethodAttribute特性声明。 的本地化字符串。
        /// </summary>
        internal static string EOS001C_Description {
            get {
                return ResourceManager.GetString("EOS001C_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 声明了事件码的类型中缺少对事件方法的定义的声明 的本地化字符串。
        /// </summary>
        internal static string EOS001C_MessageFormat {
            get {
                return ResourceManager.GetString("EOS001C_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 声明了事件码的类型中缺少对事件方法的定义的声明 的本地化字符串。
        /// </summary>
        internal static string EOS001C_Title {
            get {
                return ResourceManager.GetString("EOS001C_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方法上有EventListenerAttribute特性，但是没有类型参数，未定义作为事件接收者的该方法应当接收的事件。 的本地化字符串。
        /// </summary>
        internal static string EOS001L_Description {
            get {
                return ResourceManager.GetString("EOS001L_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 声明的事件方法接收者缺少指向的事件码 的本地化字符串。
        /// </summary>
        internal static string EOS001L_MessageFormat {
            get {
                return ResourceManager.GetString("EOS001L_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 声明的事件方法接收者缺少指向的事件码 的本地化字符串。
        /// </summary>
        internal static string EOS001L_Title {
            get {
                return ResourceManager.GetString("EOS001L_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 利用方法名称和参数进行动态绑定时，输入的方法名称与参数类型必须匹配类型实例中的唯一方法 的本地化字符串。
        /// </summary>
        internal static string EOS002AOR_Description {
            get {
                return ResourceManager.GetString("EOS002AOR_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请确认添加或移除事件时输入的方法名称 {0} 和其参数定义可以唯一确定 的本地化字符串。
        /// </summary>
        internal static string EOS002AOR_MessageFormat {
            get {
                return ResourceManager.GetString("EOS002AOR_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认添加或移除事件时输入的方法名称和参数定义可以被反射查找 的本地化字符串。
        /// </summary>
        internal static string EOS002AOR_Title {
            get {
                return ResourceManager.GetString("EOS002AOR_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非泛型广播方法要求第一个参数为字符串或类型事件码 的本地化字符串。
        /// </summary>
        internal static string EOS002B_Description {
            get {
                return ResourceManager.GetString("EOS002B_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未输入应当广播的事件的事件码 的本地化字符串。
        /// </summary>
        internal static string EOS002B_MessageFormat {
            get {
                return ResourceManager.GetString("EOS002B_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未输入应当广播的事件的事件码 的本地化字符串。
        /// </summary>
        internal static string EOS002B_Title {
            get {
                return ResourceManager.GetString("EOS002B_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型属性的Get和Set方法不能作为事件方法的声明 的本地化字符串。
        /// </summary>
        internal static string EOS002C_Description {
            get {
                return ResourceManager.GetString("EOS002C_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能将属性方法作为事件方法的声明 的本地化字符串。
        /// </summary>
        internal static string EOS002C_MessageFormat {
            get {
                return ResourceManager.GetString("EOS002C_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能将属性方法作为事件方法的声明 的本地化字符串。
        /// </summary>
        internal static string EOS002C_Title {
            get {
                return ResourceManager.GetString("EOS002C_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件方法上的EventListenerAttribute特性的参数填写的类型，未声明EventCodeAttribute特性，不能作为事件码使用。 的本地化字符串。
        /// </summary>
        internal static string EOS002L_Description {
            get {
                return ResourceManager.GetString("EOS002L_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件方法指向的事件码类型 {0} 参数未定义 的本地化字符串。
        /// </summary>
        internal static string EOS002L_MessageFormat {
            get {
                return ResourceManager.GetString("EOS002L_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件方法指向的事件码类型参数未定义 的本地化字符串。
        /// </summary>
        internal static string EOS002L_Title {
            get {
                return ResourceManager.GetString("EOS002L_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能单独使用解析为null的实例作为事件接收者 的本地化字符串。
        /// </summary>
        internal static string EOS003AOR_Description {
            get {
                return ResourceManager.GetString("EOS003AOR_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加或移除事件接收者时，试图添加或移除项目上下文不支持的类型或null引用 的本地化字符串。
        /// </summary>
        internal static string EOS003AOR_MessageFormat {
            get {
                return ResourceManager.GetString("EOS003AOR_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加或移除事件接收者时，试图添加或移除项目上下文不支持的类型或null引用 的本地化字符串。
        /// </summary>
        internal static string EOS003AOR_Title {
            get {
                return ResourceManager.GetString("EOS003AOR_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不推荐直接使用字符串作为事件码，EOS分析器无法追踪以字符串进行的广播，无法验证事件码的合法性和参数的准确性 的本地化字符串。
        /// </summary>
        internal static string EOS003B_Description {
            get {
                return ResourceManager.GetString("EOS003B_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不推荐直接使用字符串作为事件码 的本地化字符串。
        /// </summary>
        internal static string EOS003B_MessageFormat {
            get {
                return ResourceManager.GetString("EOS003B_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不推荐直接使用字符串作为事件码 的本地化字符串。
        /// </summary>
        internal static string EOS003B_Title {
            get {
                return ResourceManager.GetString("EOS003B_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一个事件码中，只有第一个声明的事件方法的定义有效。此处为多余的事件方法的定义。 的本地化字符串。
        /// </summary>
        internal static string EOS003C_Description {
            get {
                return ResourceManager.GetString("EOS003C_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过多的事件方法的定义声明 的本地化字符串。
        /// </summary>
        internal static string EOS003C_MessageFormat {
            get {
                return ResourceManager.GetString("EOS003C_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过多的事件方法的定义声明 的本地化字符串。
        /// </summary>
        internal static string EOS003C_Title {
            get {
                return ResourceManager.GetString("EOS003C_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件方法上的EventListenerAttribute特性的参数填写的类型中，不包含声明了EventCodeMethodAttribute特性的方法，事件码定义不完整。 的本地化字符串。
        /// </summary>
        internal static string EOS003L_Description {
            get {
                return ResourceManager.GetString("EOS003L_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指向的事件码类型 {0} 未声明事件方法定义 的本地化字符串。
        /// </summary>
        internal static string EOS003L_MessageFormat {
            get {
                return ResourceManager.GetString("EOS003L_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指向的事件码类型未声明事件方法定义 的本地化字符串。
        /// </summary>
        internal static string EOS003L_Title {
            get {
                return ResourceManager.GetString("EOS003L_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的事件接收者对应的类型必须是使用了EventListenerAttribute特性的类 的本地化字符串。
        /// </summary>
        internal static string EOS004AOR_Description {
            get {
                return ResourceManager.GetString("EOS004AOR_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加或移除事件接收者时，输入参数 {0} 对应的类型 {1} 不是已定义的事件接收者类型 的本地化字符串。
        /// </summary>
        internal static string EOS004AOR_MessageFormat {
            get {
                return ResourceManager.GetString("EOS004AOR_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加或移除事件接收者时，输入参数对应的类型不是已定义的事件接收者类型 的本地化字符串。
        /// </summary>
        internal static string EOS004AOR_Title {
            get {
                return ResourceManager.GetString("EOS004AOR_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入事件码参数建议使用typeof常量值，而不是无法追踪的变量，以使得EOS分析器能够追踪广播的事件码定义。 的本地化字符串。
        /// </summary>
        internal static string EOS004B_Description {
            get {
                return ResourceManager.GetString("EOS004B_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建议使用常量值类型作为事件码 的本地化字符串。
        /// </summary>
        internal static string EOS004B_MessageFormat {
            get {
                return ResourceManager.GetString("EOS004B_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建议使用常量值类型作为事件码 的本地化字符串。
        /// </summary>
        internal static string EOS004B_Title {
            get {
                return ResourceManager.GetString("EOS004B_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该方法已被声明为事件方法的定义，但是声明该方法的类型未标记为事件码。请考虑将EventCodeAttribute特性添加至该类型上。 的本地化字符串。
        /// </summary>
        internal static string EOS004C_Description {
            get {
                return ResourceManager.GetString("EOS004C_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 声明了事件方法的定义但所在类型未声明为事件码 的本地化字符串。
        /// </summary>
        internal static string EOS004C_MessageFormat {
            get {
                return ResourceManager.GetString("EOS004C_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 声明了事件方法的定义但所在类型未声明为事件码 的本地化字符串。
        /// </summary>
        internal static string EOS004C_Title {
            get {
                return ResourceManager.GetString("EOS004C_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件方法的参数数量，与EventListenerAttribute特性的参数指向的事件码类型中，声明了EventCodeMethodAttribute特性的方法定义的参数的数量不符，事件方法不能使用 的本地化字符串。
        /// </summary>
        internal static string EOS004L_Description {
            get {
                return ResourceManager.GetString("EOS004L_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件方法的参数数量与指向的事件方法定义的参数数量不符 的本地化字符串。
        /// </summary>
        internal static string EOS004L_MessageFormat {
            get {
                return ResourceManager.GetString("EOS004L_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件方法的参数数量与指向的事件方法定义的参数数量不符 的本地化字符串。
        /// </summary>
        internal static string EOS004L_Title {
            get {
                return ResourceManager.GetString("EOS004L_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的事件接收者对应的类型中，使用EventListenerAttribute特性，且参数为该事件码的方法不唯一 的本地化字符串。
        /// </summary>
        internal static string EOS005AOR_Description {
            get {
                return ResourceManager.GetString("EOS005AOR_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加或移除事件接收者时，输入参数 {0} 对应的类型 {1} 中，定义的对应于此事件码 {2} 的事件方法数量不唯一 的本地化字符串。
        /// </summary>
        internal static string EOS005AOR_MessageFormat {
            get {
                return ResourceManager.GetString("EOS005AOR_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加或移除事件接收者时，输入参数对应的类型中，定义的对应于此事件码的事件方法数量错误 的本地化字符串。
        /// </summary>
        internal static string EOS005AOR_Title {
            get {
                return ResourceManager.GetString("EOS005AOR_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试广播的事件中，填入的参数比定义的事件方法的参数要多。虽然这不会影响广播的进行，但请考虑修正填入的参数数量，或者考虑定义的事件方法可能存在错误 的本地化字符串。
        /// </summary>
        internal static string EOS005B_Description {
            get {
                return ResourceManager.GetString("EOS005B_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试广播的事件 {0} 中填入的参数过多 的本地化字符串。
        /// </summary>
        internal static string EOS005B_MessageFormat {
            get {
                return ResourceManager.GetString("EOS005B_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试广播的事件中填入的参数过多 的本地化字符串。
        /// </summary>
        internal static string EOS005B_Title {
            get {
                return ResourceManager.GetString("EOS005B_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含泛型的方法不能作为事件方法的声明 的本地化字符串。
        /// </summary>
        internal static string EOS005C_Description {
            get {
                return ResourceManager.GetString("EOS005C_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能将泛型方法作为事件方法的声明 的本地化字符串。
        /// </summary>
        internal static string EOS005C_MessageFormat {
            get {
                return ResourceManager.GetString("EOS005C_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能将泛型方法作为事件方法的声明 的本地化字符串。
        /// </summary>
        internal static string EOS005C_Title {
            get {
                return ResourceManager.GetString("EOS005C_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此位置的事件方法的参数类型，与EventListenerAttribute特性的参数指向的事件码类型中，声明了EventCodeMethodAttribute特性的方法中，此位置定义的参数的类型不符，事件方法不能使用 的本地化字符串。
        /// </summary>
        internal static string EOS005L_Description {
            get {
                return ResourceManager.GetString("EOS005L_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件方法的参数类型 {0} 与指向的事件方法定义的参数类型 {1} 不符 的本地化字符串。
        /// </summary>
        internal static string EOS005L_MessageFormat {
            get {
                return ResourceManager.GetString("EOS005L_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件方法的参数类型与指向的事件方法定义的参数类型不符 的本地化字符串。
        /// </summary>
        internal static string EOS005L_Title {
            get {
                return ResourceManager.GetString("EOS005L_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以System.Type类型作为第一个参数时，必须填入第二个参数作为事件接收者对象 的本地化字符串。
        /// </summary>
        internal static string EOS006AOR_Description {
            get {
                return ResourceManager.GetString("EOS006AOR_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺少事件接收者对象 的本地化字符串。
        /// </summary>
        internal static string EOS006AOR_MessageFormat {
            get {
                return ResourceManager.GetString("EOS006AOR_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺少事件接收者对象 的本地化字符串。
        /// </summary>
        internal static string EOS006AOR_Title {
            get {
                return ResourceManager.GetString("EOS006AOR_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试进行广播的事件码类型中定义的事件方法参数类型与当前位置已填入的参数的类型不符 的本地化字符串。
        /// </summary>
        internal static string EOS006B_Description {
            get {
                return ResourceManager.GetString("EOS006B_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件广播时填入的参数类型 {0} 与定义的类型 {1} 不符 的本地化字符串。
        /// </summary>
        internal static string EOS006B_MessageFormat {
            get {
                return ResourceManager.GetString("EOS006B_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件广播时填入的参数类型与定义的类型不符 的本地化字符串。
        /// </summary>
        internal static string EOS006B_Title {
            get {
                return ResourceManager.GetString("EOS006B_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含泛型的类型不能作为事件码的声明 的本地化字符串。
        /// </summary>
        internal static string EOS006C_Description {
            get {
                return ResourceManager.GetString("EOS006C_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能将泛型类型作为事件码的声明 的本地化字符串。
        /// </summary>
        internal static string EOS006C_MessageFormat {
            get {
                return ResourceManager.GetString("EOS006C_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能将泛型类型作为事件码的声明 的本地化字符串。
        /// </summary>
        internal static string EOS006C_Title {
            get {
                return ResourceManager.GetString("EOS006C_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此类型被EventListenerAttribute特性声明为事件接收者，但是类型内没有任何添加了EventListenerAttribute特性的事件方法。请考虑在类型内声明事件方法。 的本地化字符串。
        /// </summary>
        internal static string EOS006L_Description {
            get {
                return ResourceManager.GetString("EOS006L_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 声明了事件接收者的类型 {0} 内没有任何事件方法 的本地化字符串。
        /// </summary>
        internal static string EOS006L_MessageFormat {
            get {
                return ResourceManager.GetString("EOS006L_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 声明了事件接收者的类型内没有任何事件方法 的本地化字符串。
        /// </summary>
        internal static string EOS006L_Title {
            get {
                return ResourceManager.GetString("EOS006L_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入事件接收者类型建议使用typeof常量值，而不是无法追踪的变量，以使得EOS分析器能够追踪事件接收者类型定义 的本地化字符串。
        /// </summary>
        internal static string EOS007AOR_Description {
            get {
                return ResourceManager.GetString("EOS007AOR_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建议使用常量值类型作为输入的事件接收者类型 的本地化字符串。
        /// </summary>
        internal static string EOS007AOR_MessageFormat {
            get {
                return ResourceManager.GetString("EOS007AOR_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建议使用常量值类型作为输入的事件接收者类型 的本地化字符串。
        /// </summary>
        internal static string EOS007AOR_Title {
            get {
                return ResourceManager.GetString("EOS007AOR_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试进行广播的事件码类型中定义的事件方法存在更多参数且这些参数没有定义默认值，请补全广播时输入的参数数量 的本地化字符串。
        /// </summary>
        internal static string EOS007B_Description {
            get {
                return ResourceManager.GetString("EOS007B_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试广播的事件 {0} 填入的参数不足 的本地化字符串。
        /// </summary>
        internal static string EOS007B_MessageFormat {
            get {
                return ResourceManager.GetString("EOS007B_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试广播的事件填入的参数不足 的本地化字符串。
        /// </summary>
        internal static string EOS007B_Title {
            get {
                return ResourceManager.GetString("EOS007B_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该方法已被声明为事件方法，但是声明该方法的类型未标记为事件接收者。请考虑将EventListenerAttribute特性添加至该类型上。 的本地化字符串。
        /// </summary>
        internal static string EOS007L_Description {
            get {
                return ResourceManager.GetString("EOS007L_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 声明了事件方法但所在类型未声明为事件接收者 的本地化字符串。
        /// </summary>
        internal static string EOS007L_MessageFormat {
            get {
                return ResourceManager.GetString("EOS007L_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 声明了事件方法但所在类型未声明为事件接收者 的本地化字符串。
        /// </summary>
        internal static string EOS007L_Title {
            get {
                return ResourceManager.GetString("EOS007L_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入事件接收者类型不为静态类型的情况下，事件接收者实例参数不能输入为null 的本地化字符串。
        /// </summary>
        internal static string EOS008AOR_Description {
            get {
                return ResourceManager.GetString("EOS008AOR_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非静态类型事件接收者实例参数不能为null或无法被分析器解析的类型 的本地化字符串。
        /// </summary>
        internal static string EOS008AOR_MessageFormat {
            get {
                return ResourceManager.GetString("EOS008AOR_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非静态类型事件接收者实例参数不能为null或无法解析类型 的本地化字符串。
        /// </summary>
        internal static string EOS008AOR_Title {
            get {
                return ResourceManager.GetString("EOS008AOR_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试进行广播的事件码类型中定义的事件方法存在更多参数，虽然这些参数已定义默认值，但可以考虑补全广播时输入的参数数量 的本地化字符串。
        /// </summary>
        internal static string EOS008B_Description {
            get {
                return ResourceManager.GetString("EOS008B_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试广播的事件 {0} 中可以继续填入参数，虽然这些参数存在默认值定义 的本地化字符串。
        /// </summary>
        internal static string EOS008B_MessageFormat {
            get {
                return ResourceManager.GetString("EOS008B_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件广播中有可选填入的参数存在 的本地化字符串。
        /// </summary>
        internal static string EOS008B_Title {
            get {
                return ResourceManager.GetString("EOS008B_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此位置的事件方法的参数类型，只能是EventListenerAttribute特性的参数指向的事件码类型中，声明了EventCodeMethodAttribute特性的方法中，此位置定义的参数的类型，或是其基类或接口。事件方法不能使用。 的本地化字符串。
        /// </summary>
        internal static string EOS008L_Description {
            get {
                return ResourceManager.GetString("EOS008L_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件方法的参数类型 {0} 只能为事件方法定义的参数类型 {1} ，或其基类或接口，而非相反，因为无法约束广播时传递的参数的实际类型 的本地化字符串。
        /// </summary>
        internal static string EOS008L_MessageFormat {
            get {
                return ResourceManager.GetString("EOS008L_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件方法的参数类型只能为事件方法定义的参数类型，或其基类或接口，而非相反 的本地化字符串。
        /// </summary>
        internal static string EOS008L_Title {
            get {
                return ResourceManager.GetString("EOS008L_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加或移除的事件接收者实例必须与输入的要移除类型一致 的本地化字符串。
        /// </summary>
        internal static string EOS009AOR_Description {
            get {
                return ResourceManager.GetString("EOS009AOR_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的事件接收者类型 {0} 和输入的事件接收者实例类型 {1} 不一致 的本地化字符串。
        /// </summary>
        internal static string EOS009AOR_MessageFormat {
            get {
                return ResourceManager.GetString("EOS009AOR_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的事件接收者类型和输入的事件接收者实例类型不一致 的本地化字符串。
        /// </summary>
        internal static string EOS009AOR_Title {
            get {
                return ResourceManager.GetString("EOS009AOR_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试进行广播的事件中，使用了无法被分析器追踪的参数类型（System.Object[]）。请仅在必要情况下（如使用ref out等关键字）直接使用数组类型填入 的本地化字符串。
        /// </summary>
        internal static string EOS009B_Description {
            get {
                return ResourceManager.GetString("EOS009B_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 谨慎考虑在尝试广播的事件 {0} 中填入参数类型为System.Object[]数组 的本地化字符串。
        /// </summary>
        internal static string EOS009B_MessageFormat {
            get {
                return ResourceManager.GetString("EOS009B_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件广播参数输入参数为数组 的本地化字符串。
        /// </summary>
        internal static string EOS009B_Title {
            get {
                return ResourceManager.GetString("EOS009B_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含泛型的类型不能作为事件接收者的声明 的本地化字符串。
        /// </summary>
        internal static string EOS009L_Description {
            get {
                return ResourceManager.GetString("EOS009L_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泛型类型不能作为事件接收者使用 的本地化字符串。
        /// </summary>
        internal static string EOS009L_MessageFormat {
            get {
                return ResourceManager.GetString("EOS009L_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泛型类型不能作为事件接收者使用 的本地化字符串。
        /// </summary>
        internal static string EOS009L_Title {
            get {
                return ResourceManager.GetString("EOS009L_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件广播中存在可能的null引用参数 的本地化字符串。
        /// </summary>
        internal static string EOS010B_Description {
            get {
                return ResourceManager.GetString("EOS010B_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广播事件 {0} 中填入了可能的null引用参数 的本地化字符串。
        /// </summary>
        internal static string EOS010B_MessageFormat {
            get {
                return ResourceManager.GetString("EOS010B_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件广播中可能的null引用参数 的本地化字符串。
        /// </summary>
        internal static string EOS010B_Title {
            get {
                return ResourceManager.GetString("EOS010B_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该方法声明的指向的事件码，在该事件接收者类型中，已经被其它方法使用 的本地化字符串。
        /// </summary>
        internal static string EOS010L_Description {
            get {
                return ResourceManager.GetString("EOS010L_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型中已有指向了相同事件码 {0} 的事件方法 {1} 的本地化字符串。
        /// </summary>
        internal static string EOS010L_MessageFormat {
            get {
                return ResourceManager.GetString("EOS010L_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型中已有指向了相同事件码的事件方法 的本地化字符串。
        /// </summary>
        internal static string EOS010L_Title {
            get {
                return ResourceManager.GetString("EOS010L_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件广播中此位置的填入的参数类型，只能是指向的事件码类型中，声明了EventCodeMethodAttribute特性的方法中，此位置定义的参数的类型，或是其子类或继承。事件方法不能使用。 的本地化字符串。
        /// </summary>
        internal static string EOS011B_Description {
            get {
                return ResourceManager.GetString("EOS011B_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件广播中填入的参数 {0} 必须为事件方法定义中的参数类型 {1}，或是其子类或继承，而非相反，因为无法约束事件接收者的方法中的参数类型 的本地化字符串。
        /// </summary>
        internal static string EOS011B_MessageFormat {
            get {
                return ResourceManager.GetString("EOS011B_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件广播中填入的参数必须为事件方法定义中的参数类型的子类或继承，而非相反 的本地化字符串。
        /// </summary>
        internal static string EOS011B_Title {
            get {
                return ResourceManager.GetString("EOS011B_Title", resourceCulture);
            }
        }
    }
}
